#!/usr/bin/env bash

# This script should be run after docker build and docker push has been run.

version=0.0.1

# Usage :

# label-artifacts <filename> <docker image>
# Example :

# label-artifacts shipitcon.jpg tomwillfixit/test:latest
# This will be built into docker get plugin whenever support for MacOS is finished.

if [ $# -eq 0 ];then
    echo "Usage: $0 <filename> <docker image name>"
    exit 0
fi

OS_TYPE=$(uname -s)

if [[ "${OS_TYPE}" != "Linux" ]] && [[ "${OS_TYPE}" != "Darwin" ]]; then
    echo "[ERROR] ... Detected unsupported OS type : ${OS_TYPE}. Exiting."
    exit 1
fi

array=( $@ )
len=${#array[@]}
image=${array[$len-1]}
files=${array[@]:0:$len-1}
overlay_sha_location="/var/lib/docker/image/overlay2/distribution/v2metadata-by-diffid/sha256"

for file_name in $(echo ${files});
do 
  layer_id=$(docker history "${image}" --no-trunc |grep "${file_name}" |grep -v LABEL |awk '{print $1}' |cut -d':' -f2 |cut -c1-12)
  if [ -z "${layer_id}" ];then
      	echo "No label found for file : ${file_name}"
	exit 1
  else
	rootfs=$(docker inspect $layer_id |jq -r '.[].RootFS.Layers[-1]' |cut -d":" -f2)
    	if [ "${OS_TYPE}" = "Darwin" ];then
 		file_blob_sha_mac=$(docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i cat ${overlay_sha_location}/${rootfs})
		file_blob_sha=$(echo ${file_blob_sha_mac} |jq -r '.[].Digest'|uniq)
	else
		file_blob_sha=$(cat $overlay_sha_location/$rootfs |jq -r '.[].Digest'|uniq)
	fi

	if [ -z "${file_blob_sha}" ];then
    		echo "Unable to find SHA for file : $file_name"
    		echo "Ensure you have pushed image : $image to Docker Hub"
    		exit 1
	else
		echo "File Name : $file_name"
		echo "Layer ID  : ${layer_id}"
		echo "SHA256    : ${file_blob_sha}"
		LABEL=" --label $file_name=$file_blob_sha ${LABEL}"
	fi
  fi
done

echo "Adding LABEL/s to image : $image"
echo "${LABEL}"

docker build -t $image ${LABEL} .

docker push $image
